# Use official PostgreSQL image
FROM postgres:latest

# Set environment variables used in prisma service
ENV POSTGRES_DB = wompi 
ENV POSTGRES_USER = postgres
ENV POSTGRES_PASSWORD = daniel

# Expose the PostgreSQL port
EXPOSE 5432